# Generated by Django 3.2.7 on 2021-09-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=64)),
                ('student_sex', models.CharField(max_length=3)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
